version: build no.{build}

# https://www.appveyor.com/docs/build-configuration/#build-pipeline
branches:
  only:
  - master

platform:
  - win32
  - x64

max_jobs: 4
image: Visual Studio 2015
configuration: Release

clone_depth: 1
clone_folder: c:\%APPVEYOR_PROJECT_NAME%\

environment:
  global:
    UPDATE_VERSION: 34
  matrix:
  - ARCH_DIST: win32
    CMAKE_GENERATOR: Visual Studio 14 2015
    JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
  - ARCH_DIST: win64
    CMAKE_GENERATOR: Visual Studio 14 2015 Win64
    JAVA_HOME: C:\Program Files\Java\jdk1.8.0

matrix:
  fast_finish: true
  exclude:
    - platform: win32
      ARCH_DIST: win64
    - platform: x64
      ARCH_DIST: win32

# https://www.appveyor.com/docs/environment-variables/
before_build:
- pwsh: |-
    Write-Host "Version: $Env:UPDATE_VERSION"

    # Set the platform java to be first on the path
    $Env:PATH = "$Env:JAVA_HOME;$Env:PATH"

    git clone -q https://github.com/chromiumembedded/java-cef.git "$Env:APPVEYOR_BUILD_FOLDER/src"
    cd $Env:APPVEYOR_BUILD_FOLDER/src
    mkdir "./jcef_build"
    cd "./jcef_build"

    cmake -G "$Env:CMAKE_GENERATOR" ../ 3>&1

# https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2019
build:
  project: .\src\jcef_build\jcef.sln
  parallel: true
  verbosity: normal

after_build:
- pwsh: |-
    cd $Env:APPVEYOR_BUILD_FOLDER/src/tools

    & ./compile.bat "$Env:ARCH_DIST"
    & ./make_distrib.bat "$Env:ARCH_DIST"

    cd $Env:APPVEYOR_BUILD_FOLDER/packaging
    & ./gradlew.bat -DBIN_ARTIFACT="../src/binary_distrib" --info --no-daemon jcef

artifacts:
  - path: packaging\build\distributions\*
    name: dist

before_deploy:
- pwsh: |-
    Write-Host "About to deploy artifacts..."

deploy:
- provider: JavaCefBuildDeploy
  artifact: dist
  on:
    branch: /master/
    APPVEYOR_REPO_TAG: true

after_deploy:
- pwsh: |-
    Write-Host "Deployed!"
