version: build-{build}

branches:
  only:
  - master

platform:
  - win32
  - x64

max_jobs: 2
image: Visual Studio 2015
configuration: Release

clone_depth: 1
clone_folder: c:\%APPVEYOR_PROJECT_NAME%\

environment:
  matrix:
  - ARCH_DIST: win32
    CMAKE_GENERATOR: Visual Studio 14 2015
  - ARCH_DIST: win64
    CMAKE_GENERATOR: Visual Studio 14 2015 Win64

matrix:
  fast_finish: true
  exclude:
    - platform: win32
      ARCH_DIST: win64
    - platform: x64
      ARCH_DIST: win32

# https://www.appveyor.com/docs/environment-variables/
before_build:
- pwsh: >-
    Write-Host "Platform: $Env:PLATFORM, ARCH_DIST: $Env:ARCH_DIST, GENERATOR: $Env:CMAKE_GENERATOR"

    git clone -q https://github.com/chromiumembedded/java-cef.git "$Env:APPVEYOR_BUILD_FOLDER/src"

    cd $Env:APPVEYOR_BUILD_FOLDER/src

    mkdir "./jcef_build"

    cd "./jcef_build"

    cmake -G "$Env:CMAKE_GENERATOR" ../ 3>&1

build:
  project: .\src\jcef_build\jcef.sln
  parallel: true
  verbosity: normal

after_build:
- pwsh: >-
    cd $Env:APPVEYOR_BUILD_FOLDER/src/tools

    cmd /c compile.bat "$Env:ARCH_DIST"

    cmd /c make_distrib.bat "$Env:ARCH_DIST"

    cd ../../

before_deploy:
- pwsh: >-
    cd ./packaging

    ./gradlew -DBIN_ARTIFACT="../src/binary_distrib" --info jcef

artifacts:
  - path: packaging\build\distributions\*.zip
    name: dist

deploy:
- provider: GitHub
  description: Automated release of the Java Chromium Embedded Framework based on source code in tag $(APPVEYOR_REPO_TAG_NAME).
  auth_token:
    secure: vbdorEkvzgQxLyrjmeO5E3lPkvCIdUJUT2zTzdILuXo8hLYyfffedGkRZLb5xjGR
  artifact: dist
  on:
    branch: /master/
    APPVEYOR_REPO_TAG: true

after_deploy:
- pwsh: cd ../
