version: build-{build}

branches:
  only:
  - master

platform:
  - x86
  - x64

max_jobs: 2
image: Visual Studio 2015
configuration: Release

clone_depth: 1
clone_folder: c:\%APPVEYOR_PROJECT_NAME%\

environment:
  matrix:
  - ARCH_DIST: win32
  - ARCH_DIST: win64

matrix:
  fast_finish: true
  exclude:
    - platform: x86
      ARCH_DIST: win64
    - platform: x64
      ARCH_DIST: win32

# https://www.appveyor.com/docs/environment-variables/
before_build:
- pwsh: >-
    Write-Host "Platform: $Env:PLATFORM, ARCH_DIST: $Env:ARCH_DIST"

    git clone -q https://github.com/chromiumembedded/java-cef.git "$Env:APPVEYOR_BUILD_FOLDER/src"

    cd $Env:APPVEYOR_BUILD_FOLDER/src

    mkdir "./jcef_build"

    cd "./jcef_build"

    if ($Env:PLATFORM -eq 'x86') {
      cmake -G "Visual Studio 14" ../ 3>&1
    } else {
      cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=Release ../ 3>&1
    }

build:
  project: .\src\jcef_build\jcef.sln
  parallel: true
  verbosity: normal

after_build:
- pwsh: >-
    cd $Env:APPVEYOR_BUILD_FOLDER/src/tools

    cmd /c compile.bat "$Env:ARCH_DIST"

    cmd /c make_distrib.bat "$Env:ARCH_DIST"

    cd ../../

before_deploy:
- pwsh: >-
    cd ./packaging

    ./gradlew -DBIN_ARTIFACT="../src/binary_distrib" --info jcef

deploy:
- provider: GitHub
  auth_token:
    secure: vbdorEkvzgQxLyrjmeO5E3lPkvCIdUJUT2zTzdILuXo8hLYyfffedGkRZLb5xjGR
  artifact: /build\distributions\.*/
  on:
    branch: /master/
    APPVEYOR_REPO_TAG: true

after_deploy:
- pwsh: cd ../
