language: java

addons:
  homebrew:
    packages:
      - ninja
      - ant
      - pyenv
    taps: AdoptOpenJDK/openjdk
    casks: adoptopenjdk8-openj9

  apt:
    update: true
    sources:
      - llvm-toolchain-xenial-8 # https://docs.travis-ci.com/user/installing-dependencies/#adding-apt-sources
    packages:
      - ninja-build
      - cmake
      - clang-8
      - build-essential
      - libgtk2.0-dev
git:
  depth: false

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: xenial
      compiler: clang-8
      jdk: openjdk8
      env:
        global:
          - CC=clang-8
          - CXX=clang++-8
        - ARCH_DIST=linux64
        - ARCH_DIST=linux32
    - os: osx
      osx_image: xcode10.2
      compiler: clang
      env: ARCH_DIST=macosx64
  allow_failures:
    - os: osx
  exclude:
    - os: linux
      env: ARCH_DIST=linux32 # Either travis allows 32bit builds or use docker. See https://github.com/travis-ci/travis-ci/issues/5770

# see https://github.com/travis-ci/travis-ci/issues/8408
before_install:
  - unset _JAVA_OPTIONS

before_script:
  - git clone https://github.com/chromiumembedded/java-cef.git src
  - ./apply-patches.sh ./src
  - source setup-jdk.sh

script:
  - ./build.sh src

before_deploy:
  - cd ./packaging && source ../setup-deploy.sh ../src/binary_distrib

# for encryption, see https://docs.travis-ci.com/user/encryption-keys/
deploy:
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_RELEASE_TOKEN_PRIVATE
    file_glob: true
    file: build/distributions/*
    on:
      tags: true
      repo: smac89/java-cef-build
  - provider: pages
    skip_cleanup: true
    keep_history: true
    committer_from_gh: true
    github_token: $GITHUB_TOKEN_PRIVATE
    local_dir: build/install/java-cef-build-docs
    on:
      tags: true
      repo: smac89/java-cef-build
      condition: $ARCH_DIST == 'linux64'

env:
  global:
    - secure: "WRaDo3ndQOR5ATmjE9+EDlYnIsanPB6ItvaRbahMt2WlzLYKIBMY+ASmNVoAABykOpBkoNeKS4cIEnNueCxHU0LNfZyMvTDkuRm0s0wovyKXaEwAgRgnP6xCmnZ6V8VjTWNSl43tTcF++5S3Yx+lJdLzKWx2v/hbN1/Vb7LK6guLGLvyKlg2n2N76v/3rK2C9w5haMIrDAqCPHNnxpVYPxR2Rzqs0OmkH3GFu7YUVdfQ48RWdivKIu8NPUzDZMI3IvwFm/Ba6Sdk8y0i/z21IlBMbPQwN2vQzM9kelvO3+ZLx46DaO2s1oGXvz7T2YDzsZxQz97PMms7DyMo4t6ejF9C6feQutCOuybOAWEPkxSVXQe9XvP4jQbn1JVfjK2evqFUU3OWIxiwJJYbT/QZ7Pdmp/4GqknPzCtHihE2pawzQn/B3B9mksz6/c28UoeWy2XFQ3RnipLDTBvaJo7NQm6RngbrWhFSQRHFVQqqzw3jR4LvJFX8L6+R5bueJiXExE408hu2UUXmxskQJAWmDaFsiB2QZLaILFXx9l/bUhi5pQGL4t2jp+fVSE8u3fwev16cH0kMpnr0JhN4/hA9Cviq+V8yfVs0bbjke6dCAIMxEUOl8OolJ/N2am4sekLSwITy4QUaaS4BEqkuqLne+rAEDtKER5rR6H3BhrQzDk4="
